version: '2'

services:
  netdisco-postgresql:
    image: netdisco/netdisco:latest-postgresql
    volumes:
      - nd-pgdata-volume:/var/lib/postgresql/data:Z

  netdisco-backend:
    image: netdisco/netdisco:latest-backend
    volumes:
      - nd-sitelocal-volume:/home/netdisco/nd-site-local:Z
      - nd-config-volume:/home/netdisco/environments:Z
      - nd-logs-volume:/home/netdisco/logs:Z
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
    depends_on:
      - netdisco-postgresql

  netdisco-web:
    image: netdisco/netdisco:latest-web
    volumes:
      - nd-sitelocal-volume:/home/netdisco/nd-site-local:Z
      - nd-config-volume:/home/netdisco/environments:Z
      - nd-logs-volume:/home/netdisco/logs:Z
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
    ports:
      - "5000:5000"
    depends_on:
      - netdisco-postgresql

volumes:
  nd-pgdata-volume:
    external: false
  nd-sitelocal-volume:
    external: false
  nd-config-volume:
    external: false
  nd-logs-volume:
    external: false
